name: Test
on: push

jobs:
  test:
    name: Test local sources
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Go 1.16.4
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
      - uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys:  ${{ runner.os }}-go-
      - name: Get dependencies
        run: go mod download
      - name: Run test
        run: make test